---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	voice_input(voice_input)
	extraction_worker(extraction_worker)
	supervisor(supervisor)
	submission(submission)
	get_human_representative(get_human_representative)
	error_handler(error_handler)
	__end__([<p>__end__</p>]):::last
	__start__ --> voice_input;
	error_handler -. &nbsp;end&nbsp; .-> __end__;
	error_handler -.-> get_human_representative;
	error_handler -.-> supervisor;
	extraction_worker -.-> error_handler;
	extraction_worker -.-> supervisor;
	get_human_representative --> supervisor;
	submission --> supervisor;
	supervisor -. &nbsp;end&nbsp; .-> __end__;
	supervisor -.-> error_handler;
	supervisor -.-> get_human_representative;
	supervisor -.-> submission;
	voice_input -.-> error_handler;
	voice_input -.-> extraction_worker;
	voice_input -.-> supervisor;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
